### ISSUE TITLE
Hardcoded sensor name

### ISSUE THREAD

**Issue by joao-aguizo** [ctu-mrs/mrs_pcl_tools#2]
I came across this line: https://github.com/ctu-mrs/mrs_pcl_tools/blob/b47081a536eecc58e680920861e29925fc5c2f55/src/PCLFiltration.cpp, and I am wondering if there is any particular good reason for this information information to be hard-coded instead of configurable.

**Comment by petrapa6** [comment]
Hey, do you mean [line 208](https://github.com/ctu-mrs/mrs_pcl_tools/blob/b47081a536eecc58e680920861e29925fc5c2f55/src/PCLFiltration.cpp#L208)? If yes, thanks for a great point. I just fixed that in [ab7dc62](https://github.com/ctu-mrs/mrs_pcl_tools/commit/ab7dc62cbd2aa3b29b32f296de13d161d3d144df).

**Comment by joao-aguizo** [comment]
> Hey, do you mean [line 208](https://github.com/ctu-mrs/mrs_pcl_tools/blob/b47081a536eecc58e680920861e29925fc5c2f55/src/PCLFiltration.cpp#L208)? If yes, thanks for a great point. I just fixed that in [ab7dc62](https://github.com/ctu-mrs/mrs_pcl_tools/commit/ab7dc62cbd2aa3b29b32f296de13d161d3d144df).

Yes, that was what I meant :). Can be closed.
